spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    view:
      prefix: /
      suffix: .jsp
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/**/*.xml
  type-aliases-package: com.yidu.expressproject.*

server:
  servlet:
    context-path: /express


